<a href="https://colab.research.google.com/github/chetools/CHE4061_Fall2024/blob/main/MESHDistillation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/chetools/chetools/main/tools/che5.ipynb -O che5.ipynb
!pip install importnb

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 2.7 MB/s eta 0:00:00


In [44]:
from importnb import Notebook
with Notebook():
    from che5 import Props

import numpy as np
import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)
from scipy.optimize import root_scalar, minimize_scalar, bracket
from scipy.optimize import root
from scipy.special import expit, logit
from plotly.subplots import make_subplots
from scipy.interpolate import Akima1DInterpolator
np.set_printoptions(precision=5)

In [4]:
R=8.314
p=Props(['Ethanol', 'Water'])

In [5]:
def gamma(x,T):
    tau = p.NRTL_A + p.NRTL_B/T + p.NRTL_C*np.log(T) + p.NRTL_D*T
    G=np.exp(-p.NRTL_alpha*tau)
    xG = x@G
    xtauG_xG = (x@(tau*G))/xG
    return np.exp(xtauG_xG + x@((G*(tau - xtauG_xG[None,:])/xG[None,:]).T))

In [6]:
def dewP_ideal(y, T):
    P=1./(np.sum(y/p.Pvap(T)))
    return P, y*P/p.Pvap(T)

def dewT_ideal(y, P):

    def P_dev(T):
        return dewP_ideal(y, T)[0] - P
    T = root(P_dev, 300.).x[0]

    return T,  y*P/p.Pvap(T)

In [7]:
def bubbleP_NRTL(x, T):
    Pi= x*gamma(x,T)*p.Pvap(T)
    P=np.sum(Pi)
    return P, Pi/P

def bubbleT_NRTL(x, P):

    def f(T):
        return bubbleP_NRTL(x,T)[0]-P

    #mole-fraction weighted boiling points of each component at P
    #boiling points determined via Clausius Clapeyron, using the Hvap at the normal bp
    #for each component.  p.Hvap returns the heat of vaporization of all components for each
    #temperature if an array of temperatures is given.
    Tguess=np.dot(x,1/(1/p.Tbn-np.log(P/101325)*R/np.diagonal(p.Hvap(p.Tbn))))

    res=root_scalar(f, x0=Tguess, method='secant')
    if not(res.converged):
        return "FAIL", res
    T=root_scalar(f, x0=Tguess, method='secant').root
    Pi= x*gamma(x,T)*p.Pvap(T)
    P=np.sum(Pi)

    return T, Pi/P



In [9]:
def dewP_NRTL(y, T):
    def f(vec):
        P = vec[0]
        x = expit(vec[1:])  #Ensures that mole fractions are between 0 and 1

        fug_eqs = x*gamma(x,T) * p.Pvap(T)  - y*P
        xsum_eq = 1. - np.sum(x)

        return np.r_[fug_eqs, xsum_eq]

    #Assume ideal liquid dewP calculation for initial guess of P and liquid phase composition
    Pguess, xguess= dewP_ideal(z,T)

    #f (function to zero) maps values from -inf to inf, to values between 0 and 1
    #so xguess is mapped via logit which is the inverse function of expit
    v0 = np.r_[Pguess, logit(xguess)]
    res=root(f, v0)
    if not(res.success):
        return "FAILURE", res
    return res.x[0], expit(res.x[1:])

In [10]:
def dewT_NRTL(y, P):
    def f(vec):
        T = vec[0]
        x = expit(vec[1:])  #Ensures that mole fractions are between 0 and 1

        fug_eqs = x*gamma(x,T) * p.Pvap(T)  - y*P
        xsum_eq = 1. - np.sum(x)

        return np.r_[fug_eqs, xsum_eq]

    #Assume ideal liquid dewP calculation for initial guess of P and liquid phase composition
    Tguess, xguess= dewT_ideal(z,P)

    #f (function to zero) maps values from -inf to inf, to values between 0 and 1
    #so xguess is mapped via logit which is the inverse function of expit
    v0 = np.r_[Tguess, logit(xguess)]
    res=root(f, v0)
    if not(res.success):
        return "FAILURE", res
    return res.x[0], expit(res.x[1:])

In [11]:
def flash_idealPT(z, P, T):

    K=p.Pvap(T)/P
    def rachford(VF):
        return np.sum(z*(K-1)/(VF*(K-1) +1))

    res=root_scalar(rachford, bracket=(0,1))
    VF = res.root
    x=z/(1-VF + K *VF)
    y=K*x
    return x, y, VF

In [12]:
def flash_NRTL_PT(z, P, T, maxiter = 100, tol=1e-12):

    dewP, dewx = dewP_NRTL(z, T)
    bubbleP, bubbley = bubbleP_NRTL(z,T)

    xguess = (P-dewP)/(bubbleP-dewP) * (z - dewx) +  dewx

    for i in range(maxiter):
        K=gamma(xguess,T)*p.Pvap(T)/P

        def rachford(VF):
            return np.sum(z*(K-1)/(VF*(K-1) +1))

        res=root_scalar(rachford, bracket=(0,1))
        VF = res.root
        x=z/(1-VF + K *VF)
        if (np.linalg.norm(xguess-x)<tol):
            break
        xguess = x

    y=K*x
    return x, y, VF, i

In [13]:
def flash_NRTL_PT(z, P, T, maxiter = 100, tol=1e-12):

    dewP, dewx = dewP_NRTL(z, T)
    bubbleP, bubbley = bubbleP_NRTL(z,T)

    xguess = (P-dewP)/(bubbleP-dewP) * (z - dewx) +  dewx

    for i in range(maxiter):
        K=gamma(xguess,T)*p.Pvap(T)/P

        def rachford(VF):
            return np.sum(z*(K-1)/(VF*(K-1) +1))

        res=root_scalar(rachford, bracket=(0,1))
        VF = res.root
        x=z/(1-VF + K *VF)
        if (np.linalg.norm(xguess-x)<tol):
            break
        xguess = x

    y=K*x
    return x, y, VF, i



In [77]:
Nc = p.Mw.size
Ftot = 2.
z = np.array([0.5,0.5])
P = 1e5
dewT, _ = dewT_NRTL(z, P)
bubbleT, _ = bubbleT_NRTL(z,P)
feedT = (bubbleT + dewT)/2
x,y, vf, _ = flash_NRTL_PT(z, P, feedT)
feedH=p.Hv(Ftot*vf*y, feedT) + p.Hl(Ftot*(1-vf)*x,feedT)

In [78]:
D = 1.
Btot = Ftot - D
R = 5.
Ns = 10
Nf = 8

unk = np.zeros((Ns, 2*Nc+1))
Ltot_rec = R*D
Ltot_strip = Ltot_rec + Ftot*(1-vf)
Vtot_rec = R*D + D
Vtot_strip = Vtot_rec - Ftot*vf
unk[:Nf,:Nc] = Ltot_rec*y
unk[Nf:-1,:Nc] = Ltot_strip*x
unk[-1,:Nc] = Btot*x
unk[:Nf,Nc:2*Nc ] = Vtot_rec*y
unk[Nf:,Nc:2*Nc ] = Vtot_strip*x
unk[:,-1]=np.linspace(bubbleT_NRTL(y,P)[0],dewT_NRTL(x,P)[0],Ns)

In [79]:
def stage1(vec, vec2, refluxT):
    T,T2 = vec[-1], vec2[-1]
    L,V = jnp.split(vec[:-1],2)
    L2,V2 = jnp.split(vec2[:-1],2)
    x = L/jnp.sum(L)
    y = V/jnp.sum(V)

    MB = (V2 + R*D*y - V - L)/Ftot
    EQ = x*p.NRTL_gamma(x,T)*p.Pvap(T)/P - y
    EB = (p.Hv(V2, T2) + p.Hl(R*D*y, refluxT) - p.Hv(V, T) - p.Hl(L, T))/feedH

    return jnp.r_[MB, EQ, EB]

def stage(vec1, vec, vec2, f, fH):
    T1, T,T2 = vec1[-1], vec[-1], vec2[-1]
    L1,V1 = jnp.split(vec1[:-1],2)
    L,V = jnp.split(vec[:-1],2)
    L2,V2 = jnp.split(vec2[:-1],2)
    x = L/jnp.sum(L)
    y = V/jnp.sum(V)

    MB = (f + V2 + L1 - V - L)/Ftot
    EQ = x*p.NRTL_gamma(x,T)*p.Pvap(T)/P - y
    EB = (fH + p.Hv(V2, T2) + p.Hl(L1, T1) - p.Hv(V, T) - p.Hl(L, T))/feedH

    return jnp.r_[MB, EQ, EB]


def stageN(vec1, vec):
    T1, T = vec1[-1], vec[-1]
    L1,V1 = jnp.split(vec1[:-1],2)
    L,V = jnp.split(vec[:-1],2)
    x = L/jnp.sum(L)
    y = V/jnp.sum(V)

    MB = (L1 - V - L)/Ftot
    EQ = x*p.NRTL_gamma(x,T)*p.Pvap(T)/P - y
    MB2 = (jnp.sum(L1) - jnp.sum(V) - Btot)/Ftot

    return jnp.r_[MB, EQ, MB2]

In [80]:
stage1_jac = jax.jit(jax.jacobian(stage1, (0,1)))
stage_jac = jax.jit(jax.jacobian(stage, (0,1,2)))
stageN_jac = jax.jit(jax.jacobian(stageN, (0,1)))

In [81]:
Es = np.zeros((Ns, 2*Nc+1))
Cs = np.zeros((Ns-1, 2*Nc+1, 2*Nc+1))

In [82]:
def evalEs(unk):

    L,V = np.split(unk[0,:-1],2)
    y=V/np.sum(V)
    Es[0] = stage1(unk[0], unk[1], bubbleT_NRTL(y, P)[0])
    for i in range(1, Ns-1):
        if i==Nf:
            Es[i]= stage(unk[i-1], unk[i], unk[i+1], Ftot*z, feedH)
        else:
            Es[i]= stage(unk[i-1], unk[i], unk[i+1], 0., 0.)

    Es[-1] = stageN(unk[-2], unk[-1])

    return Es

def norm_evalEs(unk):
    return np.linalg.norm(evalEs(unk))


In [83]:
for iter in range(1,25):
    Es= evalEs(unk)
    normEs = norm_evalEs(unk)
    print(iter, normEs)
    if normEs<1e-8:
        break
    B,C = stage1_jac(unk[0], unk[1],bubbleT_NRTL(y, P)[0])
    Binv = np.linalg.inv(B)
    Cs[0]= Binv @ C
    Es[0]= Binv @ Es[0]
    for i in range(1, Ns-1):
        if i==Nf:
            A,B,C = stage_jac(unk[i-1], unk[i], unk[i+1], Ftot*z, feedH)
        else:
            A,B,C= stage_jac(unk[i-1], unk[i], unk[i+1], 0., 0.)

        Binv = np.linalg.inv(B-A@Cs[i-1])
        Cs[i]=Binv@C
        Es[i]=Binv@(Es[i]-A@Es[i-1])

    A,B = stageN_jac(unk[-2], unk[-1])
    Binv = np.linalg.inv(B-A@Cs[-1])
    Es[-1] = Binv@ (Es[-1] - A@Es[-2])

    delta_unk = np.zeros_like(unk)
    delta_unk[-1]= Es[-1]
    for i in range(Ns-2,-1,-1):
        delta_unk[i]= Es[i]-Cs[i] @ delta_unk[i+1]

    brac = bracket(lambda t: norm_evalEs(unk + t*delta_unk), xa=0., xb=1.)
    t = minimize_scalar(lambda t: norm_evalEs(unk + t*delta_unk), brac[:3]).x
    unk = unk + t*delta_unk

1 2.3333682340206927
2 0.11928611141200018
3 0.0054482895475578665
4 1.0091299778163497e-05
5 1.1699149400031717e-10


In [84]:
unk

array([[4.11529e+00, 8.79260e-01, 5.02819e+00, 9.71814e-01, 3.51119e+02],
       [4.03326e+00, 9.55338e-01, 4.95333e+00, 1.04123e+00, 3.51153e+02],
       [3.94046e+00, 1.04142e+00, 4.87130e+00, 1.11731e+00, 3.51197e+02],
       [3.83152e+00, 1.14246e+00, 4.77849e+00, 1.20339e+00, 3.51257e+02],
       [3.69780e+00, 1.26648e+00, 4.66955e+00, 1.30443e+00, 3.51343e+02],
       [3.52404e+00, 1.42751e+00, 4.53583e+00, 1.42844e+00, 3.51472e+02],
       [3.28001e+00, 1.65331e+00, 4.36207e+00, 1.58948e+00, 3.51686e+02],
       [2.89445e+00, 2.00848e+00, 4.11804e+00, 1.81528e+00, 3.52095e+02],
       [2.33876e+00, 2.92122e+00, 3.73248e+00, 2.17045e+00, 3.53094e+02],
       [1.61969e-01, 8.38031e-01, 2.17679e+00, 2.08319e+00, 3.56724e+02]])

In [85]:
L,V = np.split(unk[:,:-1],2, axis=1)
x=L/np.sum(L, axis=1)[:,None]
y=V/np.sum(V, axis=1)[:,None]

In [86]:
x,y =x[:,0], y[:,0]

In [87]:
x

array([0.82396, 0.8085 , 0.79096, 0.77031, 0.74488, 0.7117 , 0.66487,
       0.59035, 0.44463, 0.16197])

In [88]:
y

array([0.83803, 0.8263 , 0.81343, 0.79883, 0.78165, 0.7605 , 0.73293,
       0.69405, 0.63231, 0.51099])

In [89]:
opx = np.r_[y[0], np.repeat(x[:-1],2), x[-1]]
opx

array([0.83803, 0.82396, 0.82396, 0.8085 , 0.8085 , 0.79096, 0.79096,
       0.77031, 0.77031, 0.74488, 0.74488, 0.7117 , 0.7117 , 0.66487,
       0.66487, 0.59035, 0.59035, 0.44463, 0.44463, 0.16197])

In [90]:
opy=np.r_[np.repeat(y,2)]

In [91]:
P=101325
x1s=np.linspace(0,1,101)
Ts=[]
y1s=[]
for x1 in x1s:
    T, (y1,y2) = bubbleT_NRTL(np.array([x1, 1-x1]), P)
    Ts.append(T)
    y1s.append(y1)

In [92]:
fig = make_subplots()
fig.add_scatter(x=x1s, y=y1s)
fig.add_scatter(x=opx, y=opy)
fig.update_layout(width=600, height=600, template='plotly_dark')
