<a href="https://colab.research.google.com/github/chetools/CHE4061_Fall2024/blob/main/Tridiagonal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
rnd = np.random.RandomState(4214134)

In [24]:
N=5

In [69]:
A = np.diag(rnd.randint(1,10, size=N),k=0) + np.diag(rnd.randint(1,10, size=N-1),k=1) +  np.diag(rnd.randint(1,10, size=N-1),k=-1)
e = rnd.randint(1,10, size=N)

In [70]:
np.linalg.solve(A, e)

array([-0.55692308,  0.75692308, -0.03076923,  1.21846154,  0.78153846])

In [71]:
cs = np.zeros(N-1)
es = np.zeros(N)

In [72]:
cs[0] = A[0,1]/A[0,0]
es[0] = e[0]/A[0,0]

In [77]:
for i in range(1,N-1):
    a, b, c = A[i, i-1:i+2]
    b = b - a*cs[i-1]
    cs[i] = c/b
    es[i] = (e[i] - a*es[i-1])/b

a, b= A[N-1, N-2], A[N-1, N-1]
b = b - a*cs[N-2]
es[-1] = (e[-1]- a*es[-2])/b

In [78]:
x = np.zeros(N)
x[-1] = es[-1]
for i in range(N-2,-1,-1):
    x[i]= es[i]-cs[i]*x[i+1]

In [79]:
x

array([-0.55692308,  0.75692308, -0.03076923,  1.21846154,  0.78153846])

In [80]:
np.linalg.solve(A,e)

array([-0.55692308,  0.75692308, -0.03076923,  1.21846154,  0.78153846])